### ISSUE TITLE
Julia could not be started.

### ISSUE THREAD

**Issue by HerAdri** [JunoLab/atom-ink#186] opened 2018-12-21 23:12 UTC
[We tried to launch Julia from:
C:\Users\user\AppData\Local\Julia-1.0.3\bin\julia.exe

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.9.13

### Stack Trace

Uncaught TypeError: Cannot read property 'syncScrollArea' of undefined

```
At C:\Users\user\.atom\packages\ink\node_modules\xterm\lib\InputHandler.js:825

TypeError: Cannot read property 'syncScrollArea' of undefined
    at InputHandler.resetMode (/packages/ink/node_modules/xterm/lib/InputHandler.js:825:45)
    at /packages/ink/node_modules/xterm/lib/InputHandler.js:123:84
    at EscapeSequenceParser.parse (/packages/ink/node_modules/xterm/lib/EscapeSequenceParser.js:371:25)
    at InputHandler.parse (/packages/ink/node_modules/xterm/lib/InputHandler.js:200:22)
    at Terminal._innerWrite (/packages/ink/node_modules/xterm/lib/Terminal.js:876:32)
    at /packages/ink/node_modules/xterm/lib/Terminal.js:858:23
```

### Commands

```
     -2:09.9.0 julia-client:run-file (input.hidden-input)
     -2:09.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -2:09.9.0 inline-results:clear-all (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
cobalt2-syntax 0.5.3 
ink 0.9.13 
julia-client 0.7.11 
kobalt-ui 0.5.1 
language-julia 0.18.0 
latex-completions 0.3.6 
tool-bar 1.1.11 
uber-juno 0.2.0 
```

Please open your issue at https://github.com/JunoLab/Juno.jl/issues/new unless you've been explicitly pointed here by a Juno developer.

**Comment by pfitzseb** [comment] 2018-12-22 09:53
Duplicate of https://github.com/JunoLab/atom-ink/issues/185, will be fixed with the next ink release. Thanks for reporting!

**Closed as completed by pfitzseb** 2018-12-22 09:53 UTC
