### ISSUE TITLE
Uncaught TypeError: Object.observe is not a function

### ISSUE THREAD

**Issue by christianlask** [JunoLab/atom-ink#73] opened 2016-08-23 10:32 UTC
[Enter steps to reproduce below:]
1. After a fresh start I opened a Clojure file.
2. I connect to a running repl with ``proto-repl`  - after that, the error pops up repeatedly.

**Atom Version**: 1.9.9
**System**: linux 4.7.1-1-ARCH
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package, v0.5.0
### Stack Trace

Uncaught TypeError: Object.observe is not a function

```
At /home/hiberno/.atom/packages/ink/lib/console/view.coffee:102

TypeError: Object.observe is not a function
    at ink-console.ConsoleElement.observeKey (/home/hiberno/.atom/packages/ink/lib/console/view.coffee:102:12)
    at ink-console.ConsoleElement.streamView (/home/hiberno/.atom/packages/ink/lib/console/view.coffee:152:6)
    at ink-console.ConsoleElement.infoView (/home/hiberno/.atom/packages/ink/lib/console/view.coffee:161:24)
    at ink-console.ConsoleElement.initView (/home/hiberno/.atom/packages/ink/lib/console/view.coffee:39:18)
    at ink-console.ConsoleElement.addItem (/home/hiberno/.atom/packages/ink/lib/console/view.coffee:44:15)
    at ink-console.ConsoleElement.initialize (/home/hiberno/.atom/packages/ink/lib/console/view.coffee:31:8)
    at Object.createView (/home/hiberno/.atom/packages/ink/lib/util/pane-item.coffee:26:19)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/lib/atom/src/view-registry.js:119:78)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/lib/atom/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/usr/lib/atom/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/usr/lib/atom/src/pane-element.js:51:55)
```
### Commands

```
     -6:38.1.0 vim-mode-plus:move-down (atom-text-editor.editor.indent-mode-76f60.normal-mode.vim-mode-plus.is-focused)
     -6:38 vim-mode-plus:move-up (atom-text-editor.editor.indent-mode-76f60.normal-mode.vim-mode-plus.is-focused)
 75x -6:37.6.0 vim-mode-plus:move-down (atom-text-editor.editor.indent-mode-76f60.normal-mode.vim-mode-plus.is-focused)
  8x -5:52.7.0 vim-mode-plus:move-up (atom-text-editor.editor.indent-mode-76f60.normal-mode.vim-mode-plus.is-focused)
 35x -5:51 vim-mode-plus:move-down (atom-text-editor.editor.indent-mode-76f60.normal-mode.vim-mode-plus.is-focused)
     -1:27.3.0 proton:toggle (atom-text-editor.editor.indent-mode-76f60.normal-mode.vim-mode-plus.is-focused)
  2x -1:27.1.0 proton:chain (atom-text-editor.editor.indent-mode-76f60.normal-mode.is-focused)
     -1:25 proton:toggle (atom-text-editor.editor.indent-mode-76f60.normal-mode.is-focused.vim-mode-plus)
  3x -1:24.8.0 proton:chain (atom-text-editor.editor.indent-mode-76f60.normal-mode.is-focused)
     -1:23.4.0 proto-repl:remote-nrepl-connection (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.seti-icons.seti-roboto.seti-animate.theme-seti-syntax.theme-seti-ui)
     -1:13.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:25.8.0 proton:toggle (atom-pane.pane.active)
  2x -0:25.6.0 proton:chain (atom-pane.pane.active)
     -0:24 core:cancel (atom-pane.pane.active)
     -0:22.5.0 proton:toggle (atom-pane.pane.active)
  2x -0:22.3.0 proton:chain (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "relative-numbers",
      "metrics",
      "autoupdate-packages",
      "welcome",
      "about"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-beautify, v0.29.10 (inactive)
atom-dark-fusion-syntax, v1.2.0 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.4 (inactive)
atom-mdtoc, v0.8.3 (inactive)
atomatigit, v1.5.5 (active)
autocomplete-bibtex, v0.6.2 (active)
autocomplete-paths, v1.0.2 (active)
blame, v0.10.0 (inactive)
build, v0.65.0 (active)
build-cargo, v0.16.0 (active)
busy, v0.6.0 (active)
easy-motion-redux, v1.1.1 (active)
environment, v1.2.0 (active)
ex-mode, v0.13.0 (inactive)
expand-region, v0.2.4 (inactive)
file-icons, v1.7.18 (active)
git-history, v3.2.0 (inactive)
git-plus, v5.16.2 (inactive)
golden-ratio, v0.3.0 (inactive)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
ink, v0.5.0 (active)
language-diff, v0.4.0 (active)
language-latex, v0.6.1 (active)
language-puppet, v0.21.0 (active)
language-rust, v0.4.6 (active)
latex, v0.35.0 (inactive)
latexer, v0.3.0 (active)
lines, v0.13.1 (inactive)
linter, v1.11.16 (active)
linter-clojure, v1.1.2 (active)
linter-markdown, v2.0.1 (active)
linter-puppet-lint, v0.7.0 (active)
linter-rust, v0.5.4 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-writer, v2.5.1 (inactive)
maximize-panes, v0.2.0 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.24.7 (active)
move-panes, v0.2.0 (inactive)
nucleus-dark-ui, v0.9.3 (inactive)
Parinfer, v1.16.0 (active)
pdf-view, v0.50.0 (active)
pigments, v0.31.2 (active)
project-plus, v0.9.0 (active)
proto-repl, v1.4.7 (active)
proton-mode, v0.11.0 (active)
racer, v0.20.0 (active)
recent-files-fuzzy-finder, v0.2.4 (active)
relative-numbers, v0.5.1 (inactive)
release-notes, v0.53.0 (active)
seti-syntax, v1.0.1 (active)
seti-ui, v1.3.2 (active)
tab-switcher, v1.5.3 (active)
terminal-plus, v0.14.5 (active)
theme-switch, v0.4.0 (inactive)
vim-mode-plus, v0.51.0 (active)
vim-mode-plus-ex-mode, v0.5.0 (inactive)
zentabs, v0.8.7 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by pfitzseb** [comment] 2016-08-23 15:51
That's because Arch builds Atom with the newest version of Electron. 
Try a binary install from https://atom.io/ until this we fix this properly.

**Comment by christianlask** [comment] 2016-08-23 15:58
@pfitzseb Ah, thanks for the hint. And good luck fixing it :)

**Comment by malmaud** [comment] 2016-11-10 02:30
Looks like with the release of Atom 1.12, this is going to affect everyone.

**Comment by IljaK91** [comment] 2016-11-10 09:01
Have the same problem. Is there anything I can do without completely reinstalling Atom?

**Comment by pfitzseb** [comment] 2016-11-10 09:45
@malmaud Yes, definitely. This is fixed on master though, so as long as we relase that soonish there shouldn't be any problems.

@IljaK91 Not really. You could of course install ink master, but then any package that depends on it won't work 100%.

**Comment by IljaK91** [comment] 2016-11-10 09:48
@pfitzseb I don't know why, but the error disappeared after executing code for the second time. What I did was update Atom to 1.12, run "Pkg.update()" with the error described above and after running it again, I didn't see the error message anymore.

**Comment by pfitzseb** [comment] 2016-11-10 09:51
Wait, is Atom stable 1.12 already released?
You might not get the error again, but the functionality won't work either, so that's not really a solution ;)

**Comment by IljaK91** [comment] 2016-11-10 09:54
Yes, Help-> About Atom shows me that I am running version 1.12.0. Here are the changes: https://github.com/atom/atom/releases/tag/v1.12.0

**Comment by pfitzseb** [comment] 2016-11-10 10:00
Right, Atom was just slow downloading the update for me. Sigh.

**Comment by jebej** [comment] 2016-11-10 21:57
I also just hit that problem with 1.12.0.

**Comment by daschw** [comment] 2016-11-11 08:22
The issue described by @IljaK91 (error at first julia command, after that working as usual) happens at every fresh start of Atom 1.12 for me

**Comment by leocastel** [comment] 2016-11-11 16:22
I also have the same issue. I tried to use the binary version of Atom as @pfitzseb said, but it didn't work for me. I am working on Windows 7 and I really would appreciate a solution for such a problem. Is there a way to downgrade atom and use the previous version of it?

**Comment by jebej** [comment] 2016-11-11 16:25
@pfitzseb can the new version be released soon? With Atom 1.12.0 released and auto-updating, everyone will have ink/Juno broken.

**Comment by pfitzseb** [comment] 2016-11-13 15:49
This should be fixed on version 0.6.1 -- let me know if you're still having troubles.

Don't forget to call `Pkg.update()` in Julia after updating the Atom packages!

**Closed as completed by pfitzseb** 2016-11-13 15:49 UTC
Labels: bug

**Comment by malmaud** [comment] 2016-11-14 16:19
The atom editor is crashing after updating to 0.6.1. 
![screen shot 2016-11-14 at 11 18 51 am](https://cloud.githubusercontent.com/assets/987837/20272534/2c99fdfc-aa5c-11e6-9247-cd984150bbd8.png)

**Comment by malmaud** [comment] 2016-11-14 16:20
Actually, the crash is caused by upgrading julia-client

**Comment by ufechner7** [comment] 2016-11-15 19:08
Somehow the quality insurance should be improved. No idea how, though.

**Comment by pfitzseb** [comment] 2016-11-15 19:14
Getting our integration tests running on Travis would help a lot (see https://github.com/JunoLab/atom-julia-client/pull/236), but the issue @malmaud had was probably just an upgrade problem that wouldn't have been caught by that anyways.

**Comment by Chengyyt** [comment] 2016-11-30 04:19
My Atom is 1.12.6, I have the same issue. And I did what @IljaK91 said, but it didn't work for me. Is there any other solution?

**Comment by pfitzseb** [comment] 2016-11-30 10:30
Are you on the newest version of `ink` (should be 0.6.1)? If not, please update!

**Comment by Chengyyt** [comment] 2016-11-30 23:46
Hi Sebastian,

Thanks for your email. I updated the version of ink, but the new issue
comes,  it shows like this:
[image: Inline image 1]
Can you help me to solve it?
By the way, I have some problem with Juno on my laptop as well, and it
shows like this:

[image: Inline image 2]
Actually, I have already updated my Julia to the version 0.5.0 and
uninstalled the version 0.4.6.

Can you also help with this one as well?

Thank you so much.

Regards,

Cheng




*Cheng Cheng*
*Ph.D. Candidate at the University of Melbourne*

P: 0431737973
E: ccheng3@student.unimelb.edu.au

**Comment by Chengyyt** [comment] 2016-12-01 05:27
Hi Sebastian,

I found the solution for the problems, thanks a lot.

Best regards,

Cheng



*Cheng Cheng*
*Ph.D. Candidate at the University of Melbourne*

P: 0431737973
E: ccheng3@student.unimelb.edu.au

On Thu, Dec 1, 2016 at 10:46 AM, Cheng Cheng <ccheng3@student.unimelb.edu.au
> wrote:

> Hi Sebastian,
>
> Thanks for your email. I updated the version of ink, but the new issue
> comes,  it shows like this:
> [image: Inline image 1]
> Can you help me to solve it?
> By the way, I have some problem with Juno on my laptop as well, and it
> shows like this:
>
> [image: Inline image 2]
> Actually, I have already updated my Julia to the version 0.5.0 and
> uninstalled the version 0.4.6.
>
> Can you also help with this one as well?
>
> Thank you so much.
>
> Regards,
>
> Cheng
>
>
>
>
> *Cheng Cheng*
> *Ph.D. Candidate at the University of Melbourne*
>
> P: 0431737973
> E: ccheng3@student.unimelb.edu.au
>
> On Wed, Nov 30, 2016 at 9:30 PM, Sebastian Pfitzner <

**Comment by pfitzseb** [comment] 2016-12-01 11:47
Glad you got it working!
