### ISSUE TITLE
Uncaught TypeError: _this.next is not a function

### ISSUE THREAD

**Issue by WalterGR** [JunoLab/atom-ink#134] opened 2017-06-03 01:59 UTC
This may be a bug in [proto-repl](https://github.com/jasongilman/proto-repl).  Let me know if I should open this there.

1. Start Atom.
2. Open a REPL using proto-repl.
3. Press alt-down or otherwise execute the command `console:next-in-history`.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.10.5
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.6.5

### Stack Trace

Uncaught TypeError: _this.next is not a function

```
At /Users/walter/.atom/packages/ink/lib/console/console.js:59

TypeError: _this.next is not a function
    at /packages/ink/lib/console/console.js:59:45)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/walter/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Users/walter/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/walter/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/walter/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/walter/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Users/walter/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:26 core:cancel (input.hidden-input)
     -0:25.9.0 inline:clear-current (input.hidden-input)
     -0:25.9.0 editor:consolidate-selections (input.hidden-input)
     -0:25.9.0 core:cancel (input.hidden-input)
     -0:25.7.0 inline:clear-current (input.hidden-input)
     -0:25.7.0 editor:consolidate-selections (input.hidden-input)
     -0:25.7.0 core:cancel (input.hidden-input)
     -0:25.6.0 inline:clear-current (input.hidden-input)
     -0:25.6.0 editor:consolidate-selections (input.hidden-input)
     -0:25.6.0 core:cancel (input.hidden-input)
     -0:21.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:21.2.0 settings-view:open (input.hidden-input)
     -0:07.9.0 console:previous-in-history (input.hidden-input)
  2x -0:07.0 console:next-in-history (input.hidden-input)
  2x -0:06.9.0 console:previous-in-history (input.hidden-input)
     -0:00.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
ctrl-dir-scroll 0.2.3 
darkular-syntax 0.3.0 
ink 0.6.5 
proto-repl 1.4.16 
```

**Comment by pfitzseb** [comment] 2017-06-06 10:10
This basically is a duplicate of https://github.com/JunoLab/atom-ink/issues/124, and is fixed on master as well.

**Closed as completed by pfitzseb** 2017-06-06 10:10 UTC
