### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isWrapped' of undefined

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/atom-ink#164] opened 2018-05-01 04:28 UTC
Just shows up randomly.

**Atom**: 1.26.1 ia32
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.8.4

### Stack Trace

Uncaught TypeError: Cannot read property 'isWrapped' of undefined

```
At C:\Users\Chris\.atom\packages\ink\node_modules\xterm\lib\Linkifier.js:112

TypeError: Cannot read property 'isWrapped' of undefined
    at Linkifier._linkifyRow (/packages/ink/node_modules/xterm/lib/Linkifier.js:112:71)
    at Linkifier._linkifyRows (/packages/ink/node_modules/xterm/lib/Linkifier.js:54:18)
    at /packages/ink/node_modules/xterm/lib/Linkifier.js:49:69
```

### Commands

```
     -0:11.1.0 julia-client:kill-julia (textarea.xterm-helper-textarea)
     -0:10.9.0 julia-client:clear-console (textarea.xterm-helper-textarea)
     -0:00.5.0 core:confirm (textarea.xterm-helper-textarea)
```

### Non-Core Packages

```
busy-signal 1.4.3 
color-picker 2.3.0 
hidpi 0.14.0 
ink 0.8.4 
intentions 1.1.5 
julia-client 0.6.12 
language-julia 0.16.0 
language-latex 1.1.1 
language-mathematica 0.3.2 
language-matlab 0.2.1 
language-weave 0.4.3 
latex 0.50.0 
latex-completions 0.3.3 
line-count 0.5.0 
linter 2.2.0 
linter-ui-default 1.7.1 
markdown-preview-plus 2.5.8 
merge-conflicts 1.4.5 
replace-notepad 0.2.1 
Sublime-Style-Column-Selection 1.7.4 
tool-bar 1.1.7 
```

**Comment by pfitzseb** [comment] 2018-06-29 08:43
Seems to be fixed on latest xterm.js version

**Comment by nhavt** [comment] 2018-08-19 15:09
Could someone let me know how to fix this issue as I still got this issue? Thanks in advance!

**Comment by pfitzseb** [comment] 2018-08-19 15:24
What versions of ink and julia-client are you using? I haven't seen this issue around in quite some time, but if you could tell me how to reproduce it then I'd be happy to look into it.

**Comment by nhavt** [comment] 2018-08-19 16:36
Thanks very much for looking at this issue. I am using ink 0.9.4 and julia-client 0.7.3 (see this issue in this attached file [ink_error.txt](https://github.com/JunoLab/atom-ink/files/2300465/ink_error.txt). Thanks in advance!

**Comment by pfitzseb** [comment] 2018-08-22 10:30
Fixed with https://github.com/JunoLab/atom-ink/commit/70cc218b07ec08cc48521d2524039b519592ed70.

**Closed as completed by pfitzseb** 2018-08-22 10:30 UTC
Labels: bug, upstream

**Comment by nhavt** [comment] 2018-08-22 13:43
Thanks very much for looking my issue. So, I suppose to integrate those changes that you made to the installed ink folder on my computer. Or is it possible to just update those changes via Atom updates?

**Comment by pfitzseb** [comment] 2018-08-22 14:47
Once the next version of ink is out (which should be soon, I think) you can just upgrade it in Atom.

**Comment by nhavt** [comment] 2018-08-22 15:08
Ok, thanks for your help!
