### ISSUE TITLE
Ink 0.4.0 messes with Atom window size

### ISSUE THREAD

**Issue by m0nhawk** [JunoLab/atom-ink#37] opened 2016-02-27 23:01 UTC
After updating to Ink 0.4.0 it starts to messes with Atom window size and positioning: it position window in the (0, 0) with height of 100% of screen resolution and 50% width.

**Comment by Allardvm** [comment] 2016-02-28 13:07
I also ran into this issue. Atom no longer saves the window size and position on my Mac (El Capitan) upon closing. When I disable the Ink package, everything works as expected.

**Comment by pfitzseb** [comment] 2016-02-28 13:43
This is due to [those](https://github.com/JunoLab/atom-ink/blob/294c6181b681f54aadfad9cba891c6340e5be080/lib/ink.coffee#L21-L23) lines -- no clue why this should change anything about the window size though. 

Seems a bit like a bug in Atom: Similar calls involving editors, e.g. `atom.workspace.getTextEditors()`, change the window size as well when called in the `activate` function.

Possibly related: https://github.com/atom/atom/pull/9664

**Comment by MikeInnes** [comment] 2016-03-02 12:26
Those lines have been there for a while, but perhaps they're interacting badly with the new deserialisation code? Either way, editors actually already have IDs, so we should just replace that code.

**Comment by pfitzseb** [comment] 2016-03-02 12:49
IIRC this issue has been around for quite a while as well (at least for me, but I just never attributed it to ink).

**Comment by pfitzseb** [comment] 2016-03-02 18:54
Yeah, I don't quite know why I thought those lines were the culprit -- can't reproduce the behaviour I saw when testing a few days back.

That said, I'm pretty sure this is because of [those lines](https://github.com/JunoLab/atom-ink/blob/cea45feb677f6cfdfd659a6e7d51835fcaf1f677/lib/ink.coffee#L33-L35) now -- what's the failure mode this is supposed to address, @MikeInnes? I don't see any (de)serialisation problems with the console or whatever when commenting this out, but of course I don't know what to look for anyways...

**Closed as completed** 2016-03-09 12:10 UTC
